package com.project.uhdbackend.realtime.event;

public enum EventType {
	CASE_CREATED, CASE_DELETED, CASE_UPDATED, COMMENT_CREATED, EVENT_CREATED, EVENT_UPDATED, EVENT_CLASSIFIED,
	EVENT_RECLASSIFIED, EVENT_READ, EVENT_PROCESSING, EVENT_RESOLVED, EVENT_CLOSED, EVENT_UNCLASSIFIED
}
